/*
    File Name: Current_Server_Settings_Audit.sql
    Author: Miriam Figueroa
    Created Date: 08/09/2024
    
    Description:
    This script retrieves critical system-level information about the current settings of the SQL Server instance. 
    It includes details on memory usage, locked pages, large pages allocation, and SQL Server services status. 
    This script is useful for regular auditing and ensuring that server configurations are optimal and consistent 
    with best practices.

    Expected Results:
    The script returns two result sets:
    
    1. **Process Memory Information**:
        - SQL Server Memory Usage (MB): The amount of physical memory currently used by SQL Server.
        - SQL Server Locked Pages Allocation (MB): The amount of memory allocated for locked pages.
        - SQL Server Large Pages Allocation (MB): The amount of memory allocated for large pages.
        - Page Fault Count: The number of page faults generated by SQL Server.
        - Memory Utilization Percentage: The percentage of memory utilized by SQL Server.
        - Available Commit Limit (KB): The available commit limit for the SQL Server process.
        - Process Physical Memory Low: Indicates whether the physical memory is low.
        - Process Virtual Memory Low: Indicates whether the virtual memory is low.

    2. **SQL Server Services Information**:
        - Servicename: The name of the SQL Server service.
        - Process ID: The process ID of the service.
        - Startup Type: The startup type of the service (e.g., Automatic, Manual).
        - Status: The current status of the service (e.g., Running, Stopped).
        - Last Startup Time: The last time the service was started.
        - Service Account: The account under which the service is running.
        - Is Clustered: Indicates if the service is part of a cluster.
        - Cluster Node Name: The name of the cluster node (if applicable).
        - Filename: The path to the service executable file.
        - Instant File Initialization Enabled: Indicates whether instant file initialization is enabled.
*/

-- Query 1: SQL Server Process Address Space Information (Memory and Paging Details)
SELECT 
    physical_memory_in_use_kb / 1024 AS [SQL Server Memory Usage (MB)],
    locked_page_allocations_kb / 1024 AS [SQL Server Locked Pages Allocation (MB)],
    large_page_allocations_kb / 1024 AS [SQL Server Large Pages Allocation (MB)], 
    page_fault_count,
    memory_utilization_percentage,
    available_commit_limit_kb,
    process_physical_memory_low,
    process_virtual_memory_low
FROM 
    sys.dm_os_process_memory WITH (NOLOCK) 
OPTION (RECOMPILE);

-- Query 2: SQL Server Services Information
SELECT 
    servicename, 
    process_id, 
    startup_type_desc, 
    status_desc, 
    last_startup_time, 
    service_account, 
    is_clustered, 
    cluster_nodename, 
    [filename], 
    instant_file_initialization_enabled
FROM 
    sys.dm_server_services WITH (NOLOCK) 
OPTION (RECOMPILE);
